name: decoright
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  url_launcher: ^6.3.2
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  http: ^1.6.0
  lottie: ^3.3.2
  iconsax: ^0.0.8
  shimmer: ^3.0.0
  get_storage: ^2.1.1
  logger: ^2.6.2
  smooth_page_indicator: ^2.0.1
  flutter_native_splash: ^2.4.7
  image_picker: ^1.2.1
  file_picker: ^10.3.7
  supabase_flutter: ^2.8.1
  flutter_dotenv: ^5.2.1
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  record: ^6.1.2
  audioplayers: ^6.5.1
  permission_handler: ^12.0.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/content/
    - assets/images/onboarding_images/
    - assets/images/reviews/
    - assets/logos/
    - assets/icons/
    - assets/doctors/
    - lib/l10n/


flutter_intl:
  generate: false
  arb_dir: lib/l10n
  output_dir: lib/generated

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
